apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cosanet
  labels:
    app: cosanet
spec:
  selector:
    matchLabels:
      app: cosanet
  template:
    metadata:
      labels:
        app: cosanet
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: cosanet
        image: ghcr.io/cosanet/cosanet:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9156
          protocol: TCP
        securityContext:
          privileged: true
        volumeMounts:
        - name: containerd-sock
          mountPath: /run/k3s/containerd/containerd.sock
          readOnly: false
        - name: host-netns
          mountPath: /var/run/netns
          readOnly: false
          mountPropagation: Bidirectional
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
      volumes:
      - name: containerd-sock
        hostPath:
          path: /run/k3s/containerd/containerd.sock
          type: Socket
      - name: host-netns
        hostPath:
          path: /var/run/netns
          type: DirectoryOrCreate
      - name: host-proc
        hostPath:
          path: /proc
          type: Directory
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
